plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xw.englishreader'
    compileSdk 34

    defaultConfig {
        applicationId "com.xw.englishreader"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            // 用安卓自带的 debug 签名，装到自己手机上完全够用
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
